model_name: 'coboom'
gpu: 0
ver: 'v1'
seed : 42
tmode: 'pre'
downstream_mode: 

model:
  base_momentum: 0.996
  backbone:
    type: "resnet18"
  projection:
    type: "MLP"
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256


vqconfig:
  codebook_size: 1024
  codebook_dim: 512
  commitment_beta: 0.25
  decay: 0.99


data:
  dataset: 'NIH14'
  task:
  data_pct: 100
  resize_size: 224
  data_workers: 16
  pre_bs: 64
  down_tbs: 64
  down_vbs: 64
  num_examples: 86524 

  
optimizer:
  type: lars
  base_lr: 0.08
  momentum: 0.99
  weight_decay: 1.5e-06
  total_epochs: 300
  warmup_epochs: 20
  exclude_bias_and_bn: true


checkpoint:
  resume_path:
  save_epoch: 10
  log_step: 20
  ckpt_path: 