gpu: 0
log_dir: '<path to b eset>'
exp_name: 'orig_vqssl_v1'

cb:
 num_embeddings: 1024
 embd_dims: 512
 comit_cost: 0.25
 

model:
  use_momentum: True
  base_momentum: 0.996
  
  backbone:
    type: "resnet18"
    pretrained: True
  projection:
    type: "MLP"
    input_dim: 512
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256


data:
  dataset: 'NIH'
  train_df: '/NIH_Chest-Xray-14/train_label_data.csv'
  valid_df: '/NIH_Chest-Xray-14/test_label_data.csv'
  
  resize_size: 224
  data_workers: 16
  train_batch_size: 256
  val_batch_size: 64
  dual_views: 2
  num_examples: 86524 


optimizer:
  type: lars
  base_lr: 0.02
  momentum: 0.996
  weight_decay: 0.0000015
  total_epochs: 300
  warmup_epochs: 20
  exclude_bias_and_bn: true

checkpoint:
  resume_path:
  save_epoch: 10
  ckpt_path: "<path to be set>"

log:
  log_step: 20
  log_dir: